# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 17:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todo_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='finished_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
