# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_todo_finished_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='flag',
            field=models.CharField(default='Caution', max_length=10),
        ),
    ]
