# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_todo_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='flag',
        ),
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.CharField(default='0', max_length=2),
        ),
    ]
