# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_auto_20170802_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
