# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 06:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0006_auto_20170802_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='deadline',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 8, 3, 14, 25, 30, 396000)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 8, 3, 14, 25, 30, 396000)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='finished_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 8, 3, 14, 25, 30, 396000)),
        ),
    ]
